Python/Django/todo/shouts/urls.py
from django.urls import path
from . import views

app_name = 'shouts'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/update/', views.update, name="update"),
    path('create/', views.create, name='create')
]

Python/Django/todo/todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('todos.urls')),
    path('shouts/', include('shouts.urls')),
]

Python/Django/todo/todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('check/<int:id>', views.check, name='check'),
    path('delete/<int:id>', views.delete, name='delete'),
]

Python/Django/todo/users/urls.py
from django.urls import path
from . import views

# '/users/' => 홈페이지
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
]

Python/Django/todo/shouts/models.py
from django.db import models

# Create your models here.
class Shout(models.Model):
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.title + ': ' + self.content

Python/Django/todo/todos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Todo(models.Model):
    content = models.TextField()
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

Python/Django/todo/users/models.py
from django.db import models

# Create your models here.

Python/Django/todo/shouts/forms.py
from django import forms
from .models import Shout

class ShoutForm(forms.Form):
    title = forms.CharField(max_length=30)
    content = forms.CharField(max_length=100)


class ShoutModelForm(forms.ModelForm):
    class Meta:
        model = Shout
        fields = '__all__'

        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control'
            })
        }

Python/Django/todo/shouts/views.py
from django.shortcuts import render, redirect
from .models import Shout
from .forms import ShoutForm, ShoutModelForm

# Create your views here.
def home(request):
    shouts = Shout.objects.all()
    context = {
        'shouts': shouts,
    }
    return render(request, 'shouts/home.html', context)


def create(request):
    # POST 글을 DB에 저장
    if request.method == 'POST':
        # form = ShoutForm(request.POST)
        form = ShoutModelForm(request.POST)
        if form.is_valid():
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # Shout.objects.create(title=title, content=content)
            form.save()
            return redirect('shouts:home')
    # GET 글 작성하는 form
    else:
        form = ShoutModelForm()
        context = {
            'form': form
        }
        return render(request, 'shouts/form.html', context)

def update(request, id):
    shout = Shout.objects.get(pk=id)
    if request.method == 'POST':
        form = ShoutModelForm(request.POST, instance=shout)
        if form.is_valid():
            form.save()
            return redirect('shouts:home') 
    else:
        form = ShoutModelForm(instance=shout)
        context = {
            'form': form,
        }
        return render(request, 'shouts/form.html', context)

Python/Django/todo/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    # todos에 있는 내용을 다 가져와 보여주기, 접속한 유저의 정보만 가져옴
    if request.user.is_authenticated:
        todos = request.user.todo_set.all()
    else:
        todos = ''
    return render(request, 'todos/home.html', {'todos':todos})

def create(request):
    # todos 작성하기
    content = request.POST.get('content')
    user_id = request.user.id
    # user_id = User.objects.first().id
    # completed = request.POST.get('completed')
    Todo.objects.create(content=content, user_id=user_id)

    return redirect('todos:home')

def check(request, id):
    # 특정 id를 가진 투두를 뽑아 completed = True
    todo = Todo.objects.get(pk=id)
    if todo.completed:
        todo.completed = False
    else:
        todo.completed = True
    todo.save()
    return redirect('todos:home')

def delete(request, id):
    Todo.objects.get(pk=id).delete()
    return redirect('todos:home')

Python/Django/todo/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
# '/users/' => 홈페이지
# '/users/login' => 로그인 화면

def home(request):
    return render(request, 'users/home.html')


def login_user(request):
    if request.method == "POST":
        # 만약에 username, password 넘어온 값이 DB에 저장된 값과 같다면,
        # 로그인
        # 아니면
        # 꺼지삼
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # 1. 사용자가 로그인 되었을때
            messages.success(request, "성공적으로 로그인이 되었습니다.")
            return redirect('home')
        else:
            # 2. 사용자가 로그인이 되지 않았을때
            messages.success(request, "로그인이 되지 않았습니다. 다시 시도해 주세요.")
            return redirect('login')
    else:
        # /users/login GET
        # -> 로그인 창을 render
        # /users/login POST
        # -> 로그인(유저 검증)
        return render(request, 'users/login.html')

def logout_user(request):
    # 유저를 로그아웃 시킨다.
    logout(request)
    # 유저에게 로그아웃이 되었다는 메세지를 전달한다.
    messages.success(request, "성공적으로 로그아웃 되었습니다.")
    return redirect('home')

def register(request):
    if request.method == 'POST':
        # 회원가입 시키기(DB)에 사용자 정보를 저장
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    else:
        # 회원정보를 받는 form 보여주기
        form = UserCreationForm()
        context = {
            'form': form
        }
        return render(request, 'users/register.html', context)

Python/Django/todo/shouts/templates/shouts/form.html
{% extends 'users/base.html' %}

{% block content %}
{% if request.resolver_match.url_name == 'create' %}
    <h1>문의 작성</h1>
{% else %}
    <h1>문의 수정</h1>
{% endif %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_ul}}
        <input type="submit">
    </form>
{% endblock %}

Python/Django/todo/shouts/templates/shouts/home.html
{% extends 'users/base.html' %}

{% block content %}
    <h1>고객센터</h1>
    <a href="{% url 'shouts:create' %}">문의하기</a>
    <hr>
    <h2>문의내용</h2>
    {% for shout in shouts %}
    <div>
        <p>
            id: {{shout.id}}
            제목: {{shout.title}}
            내용: {{shout.content}}
            <a href="{% url 'shouts:update' shout.id%}">수정</a>
        </p>
    </div>
    {% endfor %}
{% endblock %}

Python/Django/todo/todos/templates/todos/home.html
{% extends 'users/base.html' %}

{% block content %}
    <h1>Todo List</h1>
    <form action="{% url 'todos:create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input name="content" type="text" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-primary">만들기</button>
        </div>
    </form>
    <h3>미완료된일</h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">내용</th>
            <th scope="col">체크</th>
            <th scope="col">삭제</th>
        </tr>
        </thead>
        <tbody>
        {% for todo in todos %}
            <tr>
                {% if not todo.completed %}
                    <th scope="row">{{ todo.user }}</th>
                    <td>{{ todo.content }}</td>
                    <td>
                        <button class="btn btn-dark"><a href="{% url 'todos:check' todo.id %}"
                                                        class="text-white">체크</a>
                        </button>
                    </td>
                    <td><a href="{% url 'todos:delete' todo.id %}">삭제</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h3>완료된 일</h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">내용</th>
            <th scope="col">체크</th>
            <th scope="col">삭제</th>
        </tr>
        </thead>
        <tbody>
        {% for todo in todos %}
            <tr>
                {% if todo.completed %}
                    <th scope="row">{{ todo.user }}</th>
                    <td><strike>{{ todo.content }}</strike></td>
                    <td>
                        <button class="btn btn-dark"><a href="{% url 'todos:check' todo.id %}"
                                                        class="text-white">체크해제</a></button>
                    </td>
                    <td><a href="{% url 'todos:delete' todo.id %}">삭제</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

Python/Django/todo/users/templates/users/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">TODO APP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shouts:home' %}">고객센터</a>
            </li>
        </ul>
    </div>
</nav>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

Python/Django/todo/users/templates/users/home.html
{% extends 'users/base.html' %}

{% block content %}
    <h1 class="text-center">Welcome TODO APP</h1>
    {% if user.is_authenticated %}
        <p>이름 : {{ user.first_name }} {{ user.last_name }}</p>
        <p>이메일 : {{ user.email }}</p>
        <p>아이디 : {{ user.username }}</p>
        <p>비밀번호 : {{ user.password }}</p>
    {% endif %}
{% endblock %}

Python/Django/todo/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <h1 class="text-center mt-3">L O G I N</h1>
    <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">Username</label>
            <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp"
                   placeholder="Enter Username">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

Python/Django/todo/users/templates/users/register.html
<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>